// Code generated by entc, DO NOT EDIT.

package implant

import (
	"time"
)

const (
	// Label holds the string label denoting the implant type in the database.
	Label = "implant"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldMachineID holds the string denoting the machine_id field in the database.
	FieldMachineID = "machine_id"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// EdgeHeartbeats holds the string denoting the heartbeats edge name in mutations.
	EdgeHeartbeats = "heartbeats"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the implant in the database.
	Table = "implants"
	// HeartbeatsTable is the table that holds the heartbeats relation/edge.
	HeartbeatsTable = "heartbeats"
	// HeartbeatsInverseTable is the table name for the Heartbeat entity.
	// It exists in this package in order to avoid circular dependency with the "heartbeat" package.
	HeartbeatsInverseTable = "heartbeats"
	// HeartbeatsColumn is the table column denoting the heartbeats relation/edge.
	HeartbeatsColumn = "heartbeat_implant"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "tasks"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "task_implant"
)

// Columns holds all SQL columns for implant fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldMachineID,
	FieldLastSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLastSeenAt holds the default value on creation for the "last_seen_at" field.
	DefaultLastSeenAt func() time.Time
)
