// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (h *HeartbeatQuery) CollectFields(ctx context.Context, satisfies ...string) *HeartbeatQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		h = h.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return h
}

func (h *HeartbeatQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *HeartbeatQuery {
	return h
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (i *ImplantQuery) CollectFields(ctx context.Context, satisfies ...string) *ImplantQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		i = i.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return i
}

func (i *ImplantQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *ImplantQuery {
	return i
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (t *TaskQuery) CollectFields(ctx context.Context, satisfies ...string) *TaskQuery {
	if fc := graphql.GetFieldContext(ctx); fc != nil {
		t = t.collectField(graphql.GetOperationContext(ctx), fc.Field, satisfies...)
	}
	return t
}

func (t *TaskQuery) collectField(ctx *graphql.OperationContext, field graphql.CollectedField, satisfies ...string) *TaskQuery {
	return t
}
