// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/BradHacker/chungus/ent/heartbeat"
	"github.com/BradHacker/chungus/ent/implant"
	"github.com/BradHacker/chungus/ent/task"
)

// ImplantCreate is the builder for creating a Implant entity.
type ImplantCreate struct {
	config
	mutation *ImplantMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (ic *ImplantCreate) SetUUID(s string) *ImplantCreate {
	ic.mutation.SetUUID(s)
	return ic
}

// SetMachineID sets the "machine_id" field.
func (ic *ImplantCreate) SetMachineID(s string) *ImplantCreate {
	ic.mutation.SetMachineID(s)
	return ic
}

// SetHostname sets the "hostname" field.
func (ic *ImplantCreate) SetHostname(s string) *ImplantCreate {
	ic.mutation.SetHostname(s)
	return ic
}

// SetIP sets the "ip" field.
func (ic *ImplantCreate) SetIP(s string) *ImplantCreate {
	ic.mutation.SetIP(s)
	return ic
}

// SetLastSeenAt sets the "last_seen_at" field.
func (ic *ImplantCreate) SetLastSeenAt(t time.Time) *ImplantCreate {
	ic.mutation.SetLastSeenAt(t)
	return ic
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (ic *ImplantCreate) SetNillableLastSeenAt(t *time.Time) *ImplantCreate {
	if t != nil {
		ic.SetLastSeenAt(*t)
	}
	return ic
}

// AddHeartbeatIDs adds the "heartbeats" edge to the Heartbeat entity by IDs.
func (ic *ImplantCreate) AddHeartbeatIDs(ids ...int) *ImplantCreate {
	ic.mutation.AddHeartbeatIDs(ids...)
	return ic
}

// AddHeartbeats adds the "heartbeats" edges to the Heartbeat entity.
func (ic *ImplantCreate) AddHeartbeats(h ...*Heartbeat) *ImplantCreate {
	ids := make([]int, len(h))
	for i := range h {
		ids[i] = h[i].ID
	}
	return ic.AddHeartbeatIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (ic *ImplantCreate) AddTaskIDs(ids ...int) *ImplantCreate {
	ic.mutation.AddTaskIDs(ids...)
	return ic
}

// AddTasks adds the "tasks" edges to the Task entity.
func (ic *ImplantCreate) AddTasks(t ...*Task) *ImplantCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ic.AddTaskIDs(ids...)
}

// Mutation returns the ImplantMutation object of the builder.
func (ic *ImplantCreate) Mutation() *ImplantMutation {
	return ic.mutation
}

// Save creates the Implant in the database.
func (ic *ImplantCreate) Save(ctx context.Context) (*Implant, error) {
	var (
		err  error
		node *Implant
	)
	ic.defaults()
	if len(ic.hooks) == 0 {
		if err = ic.check(); err != nil {
			return nil, err
		}
		node, err = ic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImplantMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ic.check(); err != nil {
				return nil, err
			}
			ic.mutation = mutation
			if node, err = ic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ic.hooks) - 1; i >= 0; i-- {
			if ic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ic *ImplantCreate) SaveX(ctx context.Context) *Implant {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *ImplantCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *ImplantCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *ImplantCreate) defaults() {
	if _, ok := ic.mutation.LastSeenAt(); !ok {
		v := implant.DefaultLastSeenAt()
		ic.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *ImplantCreate) check() error {
	if _, ok := ic.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "uuid"`)}
	}
	if _, ok := ic.mutation.MachineID(); !ok {
		return &ValidationError{Name: "machine_id", err: errors.New(`ent: missing required field "machine_id"`)}
	}
	if _, ok := ic.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "hostname"`)}
	}
	if _, ok := ic.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "ip"`)}
	}
	if _, ok := ic.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "last_seen_at"`)}
	}
	return nil
}

func (ic *ImplantCreate) sqlSave(ctx context.Context) (*Implant, error) {
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ic *ImplantCreate) createSpec() (*Implant, *sqlgraph.CreateSpec) {
	var (
		_node = &Implant{config: ic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: implant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: implant.FieldID,
			},
		}
	)
	if value, ok := ic.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: implant.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := ic.mutation.MachineID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: implant.FieldMachineID,
		})
		_node.MachineID = value
	}
	if value, ok := ic.mutation.Hostname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: implant.FieldHostname,
		})
		_node.Hostname = value
	}
	if value, ok := ic.mutation.IP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: implant.FieldIP,
		})
		_node.IP = value
	}
	if value, ok := ic.mutation.LastSeenAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: implant.FieldLastSeenAt,
		})
		_node.LastSeenAt = value
	}
	if nodes := ic.mutation.HeartbeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   implant.HeartbeatsTable,
			Columns: []string{implant.HeartbeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: heartbeat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ic.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   implant.TasksTable,
			Columns: []string{implant.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: task.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ImplantCreateBulk is the builder for creating many Implant entities in bulk.
type ImplantCreateBulk struct {
	config
	builders []*ImplantCreate
}

// Save creates the Implant entities in the database.
func (icb *ImplantCreateBulk) Save(ctx context.Context) ([]*Implant, error) {
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Implant, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImplantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *ImplantCreateBulk) SaveX(ctx context.Context) []*Implant {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *ImplantCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *ImplantCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
