// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Heartbeat is the predicate function for heartbeat builders.
type Heartbeat func(*sql.Selector)

// Implant is the predicate function for implant builders.
type Implant func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
